REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Kochhar',90,'Executive');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('De Haan',90,'Executive');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Rajs',50,'Shipping');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Davies',50,'Shipping');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Matos',50,'Shipping');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Vargas',50,'Shipping');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Abel',80,'Sales');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Taylor',80,'Sales');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Whalen',10,'Administration');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Hartstein',20,'Marketing');
Insert into EXPORT_TABLE (LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME) values ('Fay',20,'Marketing');
